server:
  port: 8084
spring:
  application:
    name: Spring-data
    microservice-service:
      url: http://localhost:8082/
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Dima
    schema: camundadelivery
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
    connection-init-sql: CREATE SCHEMA IF NOT EXISTS "camundadelivery";
    schema: camundadelivery
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: camundadelivery
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none